// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisEUs.Infrastructure.Repositorios;

#nullable disable

namespace SisEUs.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("SisEUs.Domain.Checkin.Entidades.Checkin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraCheckOut")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("PinId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("SisEUs.Domain.Checkin.Entidades.CheckinPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CheckinPins");
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Apresentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAutor")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeOrientador")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Apresentacoes", (string)null);
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avaliadores")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Participantes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PinCheckin")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.ToTable("Sessao", (string)null);
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Presenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "EventoId")
                        .IsUnique();

                    b.ToTable("Presencas", (string)null);
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeUsuario.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EUserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Apresentacao", b =>
                {
                    b.HasOne("SisEUs.Domain.ContextoDeEvento.Entidades.Evento", "Evento")
                        .WithMany("Apresentacoes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Evento", b =>
                {
                    b.OwnsOne("SisEUs.Domain.ContextoDeEvento.ObjetosDeValor.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<int>("EventoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Latitude")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalizacaoLatitude");

                            b1.Property<string>("Longitude")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalizacaoLongitude");

                            b1.HasKey("EventoId");

                            b1.ToTable("Sessao");

                            b1.WithOwner()
                                .HasForeignKey("EventoId");
                        });

                    b.OwnsOne("SisEUs.Domain.ContextoDeEvento.ObjetosDeValor.Local", "Local", b1 =>
                        {
                            b1.Property<int>("EventoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Bloco")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalBloco");

                            b1.Property<string>("Campus")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalCampus");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalDepartamento");

                            b1.Property<string>("Sala")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalSala");

                            b1.HasKey("EventoId");

                            b1.ToTable("Sessao");

                            b1.WithOwner()
                                .HasForeignKey("EventoId");
                        });

                    b.Navigation("Local")
                        .IsRequired();

                    b.Navigation("Localizacao")
                        .IsRequired();
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Presenca", b =>
                {
                    b.OwnsOne("SisEUs.Domain.ContextoDeEvento.ObjetosDeValor.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<int>("PresencaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Latitude")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalizacaoLatitude");

                            b1.Property<string>("Longitude")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalizacaoLongitude");

                            b1.HasKey("PresencaId");

                            b1.ToTable("Presencas");

                            b1.WithOwner()
                                .HasForeignKey("PresencaId");
                        });

                    b.Navigation("Localizacao")
                        .IsRequired();
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeUsuario.Entidades.Usuario", b =>
                {
                    b.OwnsOne("SisEUs.Domain.ContextoDeUsuario.ObjetosDeValor.NomeCompleto", "Nome", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Nome");

                            b1.Property<string>("Sobrenome")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Sobrenome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Evento", b =>
                {
                    b.Navigation("Apresentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
